defaults:
  - model: deepspeech2
  - metrics: metrics_augs
  - datasets: inference_clean # we do not want to run inference on training data
  - dataloader: base
  - transforms: base_only_instance
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_lm: True
  kenlm_model_path: "3-gram.arpa"
  vocab_path: "librispeech-vocab.txt"

inferencer:
  device_tensors: [ "spectrogram", "text_encoded" ] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "result" # any name here, can be a dataset name
  seed: 42
  from_pretrained: "model_best_4_other.pth" # path to the pretrained model

